<a href="https://colab.research.google.com/github/V-01fe21bec107/Python_basic/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [ ]:
import numpy as np
n1=np.array([[10,20,30,40,50],[20,30,40,50,60]])
print(n1)
type(n1)

[[10 20 30 40 50]
 [20 30 40 50 60]]


numpy.ndarray

In [ ]:
#To create a 2-D array
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [ ]:
import numpy as np
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#using full we can give specific number to the 2-D array
import numpy as np
n1=np.full((3,3),4)
n1

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
import numpy as np
n1=np.full((2,2),4)
n1

array([[4, 4],
       [4, 4]])

In [ ]:
#initializing the numpy within the range using arange
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
#initializing the numpy within the range using arange
import numpy as np
n1=np.arange(10,20,2)
n1

array([10, 12, 14, 16, 18])

In [ ]:
#generating the random numbers using randint
import numpy as pd
n1=np.random.randint(1,200,5)
n1

array([71, 79, 68, 51, 96])

In [ ]:
import numpy as np
n1=np.array([[10,20,30,40,50],[30,40,50,60,70]])
n1.shape=(5,2)
n1

array([[10, 20],
       [30, 40],
       [50, 30],
       [40, 50],
       [60, 70]])

In [ ]:
#Vertical stack
import numpy as np
n1=np.array([10,20,30,40])
n2=np.array([30,45,67,45])
np.vstack((n1,n2))

array([[10, 20, 30, 40],
       [30, 45, 67, 45]])

In [ ]:
#horizontal stack
import numpy as np
n1=np.array([10,20,30,40])
n2=np.array([34,50,78,30])
np.hstack((n1,n2))

array([10, 20, 30, 40, 34, 50, 78, 30])

In [ ]:
#Column_stack
import numpy as np
n1=np.array([10,20,30,40])
n2=np.array([34,50,78,30])
np.column_stack((n1,n2))

array([[10, 34],
       [20, 50],
       [30, 78],
       [40, 30]])

Numpy intersection and difference

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50])
n2=np.array([40,50,60,70,80])
np.intersect1d(n1,n2)

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50])
n2=np.array([40,50,60,70,80])
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [ ]:
import numpy as nd
n1=nd.array([10,20,30,40])
nd.mean(n1)


25.0

In [ ]:
nd.median(n1)

25.0

In [ ]:
nd.std(n1)#for standard deviation

11.180339887498949